# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petsgame_app', '0002_pet_currenthp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petsgame_app.User')),
            ],
        ),
    ]
