# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsgame_app', '0003_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=40),
        ),
    ]
