# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsgame_app', '0004_auto_20170907_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imgurl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.CharField(max_length=20),
        ),
    ]
