# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsgame_app', '0005_auto_20171123_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='health',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='user',
            name='maxhealth',
            field=models.IntegerField(default=100),
        ),
    ]
