# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petsgame_app', '0006_auto_20171123_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='imgurl',
        ),
    ]
