# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsgame_app', '0007_auto_20171125_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
