# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsgame_app', '0008_auto_20171126_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
