# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petsgame_app', '0009_auto_20171126_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petsgame_app.User'),
        ),
    ]
